### ISSUE TITLE
Text table dump

### ISSUE THREAD

**Issue by alexevane** [everything8215/everything8215.github.io#1]
Hi everything,

This is not actually an issue but I want to ask that how can you able to dump kanji table from FF6 gba and snes ?

Thank you !!

**Comment by everything8215** [comment]
Hi, sorry I didn't see this sooner. Here are my table files for the Japanese versions:

GBA version: http://www.mediafire.com/file/8aecs046yfxf27y/ff6j-gba.tbl/file
SFC version: http://www.mediafire.com/file/6jhdelafp11pdsl/ff6j.tbl/file

**Comment by alexevane** [comment]
@everything8215 Thank you for your table files.

As for methodology, do you have to put the kanji data one by one.
Or is it some other way to work around which make it faster? 

Since it like 1000+ characters in there.

**Comment by alexevane** [comment]
@everything8215 Thank you for your table files.

As for methodology, do you have to put the kanji data one by one.
Or is it some other way to work around which make it faster?

Since it like 1000+ characters in there.

**Comment by everything8215** [comment]
I did it one by one. It was pretty tedious, especially since I don't really know Japanese. I used this website to help: https://kwhazit.ucoz.net/trans/ff6/index.html
